### ISSUE TITLE
cannot able to go fix model setting error 

### ISSUE THREAD

**Issue by xalteropsx** [absolute-quantum/cats-blender-plugin#428] opened 2022-04-15 23:46 UTC
```Python: Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: <unknown location>:-1

```

**Comment by 989onan** [comment] 2022-04-16 03:29
Duplicate of https://github.com/absolute-quantum/cats-blender-plugin/issues/379

**Comment by xalteropsx** [comment] 2022-04-16 06:17
when it going to update .u already fix it but didnt update it

**Comment by xalteropsx** [comment] 2022-04-16 06:19
and how can i avoid changing bones name when fix click   since i do modding bone name changes it fix the mesh and bone but how can i avoid bone name rename

**Closed as completed** 2022-04-19 18:13 UTC
