### ISSUE TITLE
Cannot Customize "Fix Model"

### ISSUE THREAD

**Issue by dkongp00** [absolute-quantum/cats-blender-plugin#383] opened 2022-03-12 21:07 UTC
I'm trying to fix a model by just removing the Zero Weights Bones, but every time I try to click on the Wrench Icon next to the "Fix Model" button, I get a Python Error. Any solutions?
![Blender Python Bug](https://user-images.githubusercontent.com/77458535/158035025-69cb6db8-c904-4e78-90dd-b3fca03ae695.PNG)
?

**Comment by TonyKabooch** [comment] 2022-03-12 21:32
I am having the same isse as well.

**Comment by TonyKabooch** [comment] 2022-03-12 21:36
> I'm trying to fix a model by just removing the Zero Weights Bones, but every time I try to click on the Wrench Icon next to the "Fix Model" button, I get a Python Error. Any solutions? ![Blender Python Bug](https://user-images.githubusercontent.com/77458535/158035025-69cb6db8-c904-4e78-90dd-b3fca03ae695.PNG) ?

You need to either use Blender 2.9 or 3.0 if using steam go to properties of game then betas and select from the dropdown.

**Comment by dkongp00** [comment] 2022-03-12 21:43
Roger that. Thanks for the fix!

**Comment by feilen** [comment] 2022-04-06 19:59
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 19:59 UTC
Labels: blender 3.1
