### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by BorisKalashnikov** [absolute-quantum/cats-blender-plugin#412] opened 2022-03-30 18:25 UTC
Python: Traceback (most recent call last):
  File "C:\Users\Boris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 1208, in execute
    hierarchy_check_hips = check_hierarchy(False, [
  File "C:\Users\Boris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 1275, in check_hierarchy
    Common.show_error(6.4, missing2)
  File "C:\Users\Boris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1652, in show_error
    bpy.ops.cats_common.show_error('INVOKE_DEFAULT')
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Boris\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1670, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * dpi_scale)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\modules\bpy\ops.py:130

location: <unknown location>:-1

**Comment by BorisKalashnikov** [comment] 2022-03-31 18:17
If its fixable how can I fix this?

**Comment by feilen** [comment] 2022-04-06 19:47
This is an issue with the latest version of blender, try 2.93.

**Comment by feilen** [comment] 2022-04-06 20:00
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 20:00 UTC
Labels: blender 3.1
