### ISSUE TITLE
CATS fix model not working

### ISSUE THREAD

**Issue by fizziefrogs** [absolute-quantum/cats-blender-plugin#393] opened 2022-03-19 18:44 UTC
Hello!! Currently I'm having a problem, each time I try to click fix model it seems broken and won't work when I click the wrench next to "fix model" 
![fix model](https://user-images.githubusercontent.com/101947047/159134421-5a4da0da-9686-448c-84a8-d87fcd6e8bc3.png)

**Comment by HisokaMorow044** [comment] 2022-03-21 19:31
im also dealing with this

**Comment by madalynnaline** [comment] 2022-03-23 02:29
i also have this issue

**Comment by 989onan** [comment] 2022-03-23 20:10
https://github.com/absolute-quantum/cats-blender-plugin/issues/385
https://github.com/absolute-quantum/cats-blender-plugin/pull/382

**Comment by feilen** [comment] 2022-04-06 20:00
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 20:00 UTC
Labels: blender 3.1
