### ISSUE TITLE
fix Model config tab causes traceback error in blender 3.0.1

### ISSUE THREAD

**Issue by MNS26** [absolute-quantum/cats-blender-plugin#385] opened 2022-03-13 18:25 UTC
whenever i click on the little wrench icon to the settigns of the "fix model" option it throws a traceback error (tried normal latest one and latest dev branch)
im running blender 3.0.1
![image](https://user-images.githubusercontent.com/53867268/158073670-047084dc-3201-4c51-a83f-eeafb31d3f36.png)

**Comment by 989onan** [comment] 2022-03-15 21:32
This is a known issue and already has a pull request, thanks though!

**Comment by feilen** [comment] 2022-04-06 20:00
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 20:00 UTC
Labels: blender 3.1
