### ISSUE TITLE
Button "Fix model settings" didn't work in blender 3.1

### ISSUE THREAD

**Issue by UnknoOff** [absolute-quantum/cats-blender-plugin#404] opened 2022-03-23 11:04 UTC
Greetings! When I click on the "Repair Model" button, I get the following error:
![image](https://user-images.githubusercontent.com/101591497/159683706-ce002dac-ebff-4711-8ab2-f9c8056784ce.png)

I don't know how to fix this. I reinstalled blender and all the settings with plugins so that everything worked, but everything was in vain. I checked on older versions - on the same 2.9. But on 3.0 and 3.1 - this button stupidly does not work. Please help or we gonna wait for a new update for this plugin.

**Comment by 989onan** [comment] 2022-03-23 20:03
Oh, if you're installing other versions of blender and it's still not working, make sure it's not using a different installation of python since this isn't bad coding on our part *technically* but instead a problem with how python interprets number types. Blender will still throw the error if it's still using the new version of python on other versions, which can happen if it's linked to the new version of python. I suggest looking up how to change which python Blender is using to use the one bundled in 2.93-3.0

**Comment by Toys0125** [comment] 2022-03-28 06:25
Since 3.1 is now the stable release I have issues using Cats v1.9 at all. The dev branch does seem to work though.

**Comment by feilen** [comment] 2022-04-06 20:00
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 20:00 UTC
Labels: blender 3.1
