### ISSUE TITLE
Several functions give this error in 0.19.0

### ISSUE THREAD

**Issue by KeyOfCode** [absolute-quantum/cats-blender-plugin#389] opened 2022-03-17 12:25 UTC
Python: Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\ui\armature.py", line 205, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 3.25)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: <unknown location>:-1

This includes the install a different version option, and the settings for fixing the model

**Comment by feilen** [comment] 2022-04-06 20:00
Duplicate of #379.

**Closed as completed by feilen** 2022-04-06 20:00 UTC
Labels: blender 3.1
